// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xahkzuptjpoqlcppssum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhaGt6dXB0anBvcWxjcHBzc3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4OTAyOTksImV4cCI6MjA1MTQ2NjI5OX0.4n5aB9eHOOv_sbEZ5hd3w3BFG4zyUpy-2SIXhypbE_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);